In [9]:
import math 

def basic_sigmoid(x):
    return (1/(1+math.exp(-x)))

In [10]:
print(f"sigmoid(1) = {basic_sigmoid(1)}")

sigmoid(1) = 0.7310585786300049


In [11]:
# this will generate an error
x = [1,2,3] #here x is a vector
sigmoid(x)

NameError: name 'sigmoid' is not defined

In [12]:
# numpy can easily handle this
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))
x = x+3  #it does elementwise addition
print(x)

[ 2.71828183  7.3890561  20.08553692]
[4 5 6]


<h3>Sigmoid using numpy</h3>

In [13]:
def sigmoid_np(x):
    x = np.array(x)
    sigma_x = 1/(1+np.exp(-x))
    return sigma_x

In [14]:
x = 1
print("numpy sigmoid of 1 = ", sigmoid_np(x))

numpy sigmoid of 1 =  0.7310585786300049


In [15]:
x = [1, 2, 3]
print(print("numpy sigmoid of [1,2,3] = ", sigmoid_np(x)))

numpy sigmoid of [1,2,3] =  [0.73105858 0.88079708 0.95257413]
None


<h3>Sigmoid derivative</h3>

In [16]:
def sigmoid_derivative(x):
    s = sigmoid_np(x)
    ds = s*(1-s)
    return ds

In [17]:
x = 5
print(f"sigmoid derivative of 5 = {sigmoid_derivative(x)}")
x = [1,2,3]
print(f"sigmoid derivative of [1,2,3] = {sigmoid_derivative(x)}")

sigmoid derivative of 5 = 0.006648056670790033
sigmoid derivative of [1,2,3] = [0.19661193 0.10499359 0.04517666]


In [18]:
x = np.array([[1],[2],[3]])
print(x.shape)
y = np.array([[1,2,3]])
print(y.shape)

(3, 1)
(1, 3)


In [19]:
y.reshape(3,1)

array([[1],
       [2],
       [3]])

In [42]:
# image to vector
def image2vector(image):
    v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
    return v

In [43]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(t_image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


<h3>Normalization</h3>

In [55]:
def normalizeRows(x):
    norm_x = np.linalg.norm(x, axis=1, ord=2, keepdims = True)
    x_normalized = x/norm_x
    print(x.shape)
    print(norm_x.shape)
    return x_normalized

In [56]:
x = np.array([[0., 3., 4.],
              [1., 6., 4.]])
print("normalizeRows(x) = " + str(normalizeRows(x)))


(2, 3)
(2, 1)
normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


<h3>Softmax</h3>

In [60]:
def softmax(x):
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x, axis = 1, keepdims = True)
    soft_x = exp_x/sum_exp_x
    return soft_x

In [61]:
t_x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(t_x)))


softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


<h3>Vectorization</h3>

In [77]:
import time
# x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
# x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]
x1 = np.random.rand(1000)
x2 = np.random.rand(1000)

# classic vector product implementation
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot = dot+x1[i]*x2[i]
toc = time.process_time()
print(f"dot = {dot}, computation time = {1000*(toc-tic)} ms")

# classic outer product implementation
tic = time.process_time()
outer = np.zeros((len(x1), len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print(f"outer product computation time on 1M dimensional vectors = {1000*(toc-tic)} ms")

dot = 253.20929513224306, computation time = 0.0 ms
outer product computation time on 1M dimensional vectors = 171.875 ms


In [80]:
x1 = np.random.rand(1000000)
x2 = np.random.rand(1000000)
# classic vector product implementation
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot = dot+x1[i]*x2[i]
toc = time.process_time()
print(f"dot = {dot}, normal computation time = {1000*(toc-tic)} ms")

# vectorized product of vectors
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print(f"dot = {dot}, vectorized computation time = {1000*(toc-tic)} ms")

x1 = np.random.rand(1000)
x2 = np.random.rand(1000)
# vectorized outer product
outer = np.outer(x1,x2)
toc = time.process_time()
print(f"vectorized outer product computation time = {1000*(toc-tic)} ms")

dot = 250495.9918278531, normal computation time = 281.25 ms
dot = 250495.9918278447, vectorized computation time = 0.0 ms
dot = 250495.9918278447, vectorized computation time = 0.0 ms


<h3>L1 and L2 loss functions</h3>

In [82]:
# L1 loss
def L1(yhat, y):
    loss = np.sum(abs(y-yhat))
    return loss
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat, y)))


L1 = 1.1


In [84]:
# L2 loss
def L2(yhat, y):
    loss = np.dot((y-yhat), (y-yhat))
    return loss

yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

print("L2 = " + str(L2(yhat, y)))

L2 = 0.43
