In [4]:
import math 

def sigmoid(x):
    return (1/(1+math.exp(-x)))

In [5]:
print(f"sigmoid(1) = {sigmoid(1)}")

sigmoid(1) = 0.7310585786300049


In [6]:
# this will generate an error
x = [1,2,3] #here x is a vector
sigmoid(x)

TypeError: bad operand type for unary -: 'list'

In [7]:
# numpy can easily handle this
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))
x = x+3  #it does elementwise addition
print(x)

[ 2.71828183  7.3890561  20.08553692]
[4 5 6]


In [8]:
def sigmoid_np(x):
    return (1/(1+np.exp(-x)))

In [9]:
np_arr =  np.array([1,2,3])
print("sigmoid of array = ", sigmoid_np(np_arr))

sigmoid of array =  [0.73105858 0.88079708 0.95257413]


In [10]:
def sigmoid_derivative(x):
    s = sigmoid_np(x)
    return s*(1-s)

In [11]:
sigmoid_derivative(np.array([1,2,3]))

array([0.19661193, 0.10499359, 0.04517666])

In [12]:
def image2vector(image):
    v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2], 1)
    return v

In [13]:
t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])

print(f"Image to vector: {image2vector(t_image)}")

Image to vector: [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [16]:
def normalize_rows(x):
    x_norm = np.linalg.norm(x,axis=1, keepdims=True)
    x = x/x_norm
    print(f"shape of x: {x.shape} \n Shape of x_norm: {x_norm.shape}")
    return x
    

In [17]:
x = np.array([[0., 3., 4.],
              [1., 6., 4.]])
print(f"normalized rows(x) = {normalize_rows(x)}")

shape of x: (2, 3) 
 Shape of x_norm: (2, 1)
normalized rows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


<h3>Softmax using for loops</h3>

In [27]:
def softmax1(x):
    soft_x = np.zeros((x.shape[0],x.shape[1]))
    sum_rows = np.zeros((x.shape[1], 1))
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            sum_rows[i][0] = sum_rows[i][0]+ np.exp(x[i][j])
        
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            soft_x[i][j] = np.exp(x[i][j])/sum_rows[i]
    return soft_x

<h3>Softmax using vectorization</h3>

In [28]:
def softmax2(x):
    x = np.exp(x)
    x = x/np.sum(x, axis=1, keepdims=True)
    return x

In [30]:
t_x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
print("softmax1(x) = " + str(softmax1(t_x)))
print("softmax2(x) = " + str(softmax2(t_x)))

softmax1(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]
softmax2(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


C:\Users\ASUS\AppData\Local\Temp\ipykernel_12712\419620758.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  soft_x[i][j] = np.exp(x[i][j])/sum_rows[i]
