In [1]:
import tensorflow as tf
print("tensorflow version: ", tf.__version__)

tensorflow version:  2.15.0


In [3]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 0s 0us/step


In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.30909684,  0.05971314,  0.24607933,  0.09153725, -0.06563987,
         0.14024146,  0.15695229, -0.12603796,  0.225696  ,  0.03952039]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.12129276, 0.09452113, 0.11388505, 0.09757756, 0.08338515,
        0.10244763, 0.104174  , 0.07849794, 0.11158719, 0.09263162]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.2784035

In [10]:
model.compile(optimizer = "adam",
              loss = loss_fn,
              metrics = ["accuracy"])

In [11]:
model.fit(x_train, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 11s 5ms/step - loss: 0.2979 - accuracy: 0.9129
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1452 - accuracy: 0.9574
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1098 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0892 - accuracy: 0.9721
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0779 - accuracy: 0.9752


In [12]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0722 - accuracy: 0.9788 - 907ms/epoch - 3ms/step


[0.0721898227930069, 0.9787999987602234]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.66003619e-08, 1.73916936e-10, 2.41582427e-07, 1.96825073e-04,
        3.47759386e-12, 7.65963293e-08, 5.98007646e-13, 9.99793351e-01,
        4.35935021e-07, 9.06377500e-06],
       [6.67299886e-08, 3.39264079e-05, 9.99946713e-01, 5.52713209e-06,
        4.93798948e-15, 9.68364702e-07, 3.13594022e-08, 4.12560502e-13,
        1.27520425e-05, 2.06247102e-13],
       [3.85493024e-07, 9.98411298e-01, 2.64643109e-04, 1.90622995e-05,
        1.60167809e-04, 1.65219296e-06, 2.07869271e-05, 9.66105901e-04,
        1.54108144e-04, 1.81723192e-06],
       [9.99849081e-01, 8.99151448e-11, 2.19557260e-05, 2.91571240e-07,
        3.48060176e-08, 2.52021846e-06, 9.55267096e-05, 2.16267144e-05,
        5.27653242e-07, 8.45679460e-06],
       [3.18789347e-07, 8.25433499e-10, 4.62919189e-07, 6.64369324e-08,
        9.97488379e-01, 9.15654766e-07, 5.38640325e-06, 5.33043967e-05,
        4.50403093e-07, 2.45061354e-03]], dtype=float32)>